select * from compras_oracle
select * from ventas_oracle

--Tablas

CREATE TABLE compras_oracle (
    FECHA DATE,
    CODPROVEEDOR NVARCHAR2(10),
    NOMBREPROVEEDOR NVARCHAR2(250),
    DIRECCIONPROVEEDOR NVARCHAR2(500),
    NUMEROPROVEEDOR NVARCHAR2(50),
    WEBPROVEEDOR NVARCHAR2(50),
    CODPRODUCTO NVARCHAR2(50),
    NOMBREPRODUCTO NVARCHAR2(100),
    MARCAPRODUCTO NVARCHAR2(50),
    CATEGORIA NVARCHAR2(50),
    SODSUCURSAL NVARCHAR2(50),
    NOMBRESUCURSAL NVARCHAR2(50),
    DIRECCIONSUCURSAL NVARCHAR2(500),
    REGION NVARCHAR2(50),
    DEPARTAMENTO NVARCHAR2(50),
    UNIDADES NUMBER,
    COSTO_U DECIMAL(10,2)
);


CREATE TABLE ventas_oracle (
    FECHA DATE,
    CODIGOCLIENTE NVARCHAR2(10),
    NOMBRECLIENTE NVARCHAR2(250),
    TIPOCLIENTE NVARCHAR2(50),
    DIRECCIONCLIENTE NVARCHAR2(500),
    NUMEROCLIENTE NVARCHAR2(50),
    CODVENDEDOR NVARCHAR2(50),
    NOMBREVENDEDOR NVARCHAR2(50),
    VACACIONISTA number(1),
    CODPRODUCTO NVARCHAR2(50),
    NOMBREPRODUCTO NVARCHAR2(100),
    MARCAPRODUCTO NVARCHAR2(50),
    CATEGORIA NVARCHAR2(50),
    SODSUCURSAL NVARCHAR2(50),
    NOMBRESUCURSAL NVARCHAR2(50),
    DIRECCIONSUCURSAL NVARCHAR2(500),
    REGION NVARCHAR2(50),
    DEPARTAMENTO NVARCHAR2(50),
    UNIDADES NUMBER,
    PRECIOUNITARIO NUMBER(10,2)
);

--Consultas para las dimensiones

SELECT DISTINCT 
    NVL(CODPROVEEDOR, 'N/A') AS cod_proveedor, 
    NVL(NOMBREPROVEEDOR, 'N/A') AS nombre_proveedor, 
    NVL(DIRECCIONPROVEEDOR, 'N/A') AS direccion_proveedor, 
    NVL(NUMEROPROVEEDOR, 'N/A') AS numero_proveedor, 
    NVL(WEBPROVEEDOR, 'N/A') AS web_proveedor
FROM COMPRAS_ORACLE


SELECT DISTINCT 
    NVL(CODIGOCLIENTE, 'N/A') AS codigo_cliente,
    NVL(NOMBRECLIENTE, 'N/A') AS nombre_cliente,
    NVL(TIPOCLIENTE, 'N/A') AS tipo_cliente,
    NVL(DIRECCIONCLIENTE, 'N/A') AS direccion_cliente,
    NVL(NUMEROCLIENTE, 'N/A') AS numero_cliente
FROM VENTAS_ORACLE


SELECT 
    NVL(SODSUCURSAL, 'N/A') AS sod_sucursal,
    NVL(NOMBRESUCURSAL, 'N/A') AS nombre_sucursal,
    NVL(DIRECCIONSUCURSAL, 'N/A') AS direccion_sucursal,
    NVL(REGION, 'N/A') AS region,
    NVL(DEPARTAMENTO, 'N/A') AS departamento
FROM COMPRAS_ORACLE
UNION
SELECT 
    NVL(SODSUCURSAL, 'N/A') AS sod_sucursal,
    NVL(NOMBRESUCURSAL, 'N/A') AS nombre_sucursal,
    NVL(DIRECCIONSUCURSAL, 'N/A') AS direccion_sucursal,
    NVL(REGION, 'N/A') AS region,
    NVL(DEPARTAMENTO, 'N/A') AS departamento
FROM VENTAS_ORACLE


SELECT DISTINCT 
    NVL(CODVENDEDOR, 'N/A') AS cod_vendedor,
    NVL(NOMBREVENDEDOR, 'N/A') AS nombre_vendedor,
    NVL(VACACIONISTA, 0) AS vacacionista
FROM VENTAS_ORACLE


SELECT 
    NVL(FECHA, TO_DATE('01/01/1900', 'DD/MM/YYYY')) AS fecha,
    NVL(EXTRACT(YEAR FROM FECHA), -1) AS anio,
    NVL(EXTRACT(MONTH FROM FECHA), -1) AS mes,
    NVL(EXTRACT(DAY FROM FECHA), -1) AS dia,
    NVL(TO_NUMBER(TO_CHAR(FECHA, 'Q')), -1) AS trimestre
FROM COMPRAS_ORACLE
UNION
SELECT 
    NVL(FECHA, TO_DATE('01/01/1900', 'DD/MM/YYYY')) AS fecha,
    NVL(EXTRACT(YEAR FROM FECHA), -1) AS anio,
    NVL(EXTRACT(MONTH FROM FECHA), -1) AS mes,
    NVL(EXTRACT(DAY FROM FECHA), -1) AS dia,
    NVL(TO_NUMBER(TO_CHAR(FECHA, 'Q')), -1) AS trimestre
FROM VENTAS_ORACLE




SELECT  
    NVL(CODPRODUCTO, 'N/A') AS cod_producto,
    NVL(NOMBREPRODUCTO, 'N/A') AS nombre_producto,
    NVL(MARCAPRODUCTO, 'N/A') AS marca_producto,
    NVL(CATEGORIA, 'N/A') AS categoria
FROM COMPRAS_ORACLE
UNION
SELECT 
    NVL(CODPRODUCTO, 'N/A') AS cod_producto,
    NVL(NOMBREPRODUCTO, 'N/A') AS nombre_producto,
    NVL(MARCAPRODUCTO, 'N/A') AS marca_producto,
    NVL(CATEGORIA, 'N/A') AS categoria
FROM VENTAS_ORACLE


